domain_path: C:\Users\ryand\OneDrive\Documents\Xilinx\ECE153A\Vitis\Lab1\platform_Lab1\export\platform_Lab1\sw\standalone_microblaze_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
